name: book-store-server

services:
    book-store-app:
      build: .
      container_name: book-store-app
      ports:
        - "8080:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}
        - MANAGER_PASSWORD=${MANAGER_PASSWORD}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
        - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
        - FRONTEND_URL=${FRONTEND_URL}
      depends_on:
        mysql-db:
          condition: service_healthy
        elasticsearch:
          condition: service_healthy
        minio:
          condition: service_healthy
      networks:
        bookstore-net:
          aliases:
            - backend
      restart: unless-stopped

    mysql-db:
      image: mysql:8.0
      container_name: mysql-db
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=book_store
      volumes:
        - mysql-data:/var/lib/mysql
      healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - bookstore-net
      restart: unless-stopped

    elasticsearch:
      image: elasticsearch:8.11.1
      container_name: elasticsearch
      ports:
        - "9200:9200"
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      healthcheck:
        test: [ "CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1" ]
        interval: 10s
        timeout: 5s
        retries: 10
      networks:
        - bookstore-net
      restart: unless-stopped

    minio:
      image: minio/minio:latest
      container_name: minio
      ports:
        - "9000:9000"
        - "9001:9001"
      environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=minioadmin
      command: server /data --console-address ":9001"
      volumes:
        - minio-data:/data
      healthcheck:
        test: [ "CMD", "mc", "ready", "local" ]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - bookstore-net
      restart: unless-stopped

volumes:
  mysql-data:
  elasticsearch-data:
  minio-data:

networks:
  bookstore-net:
    name: bookstore-net
    driver: bridge
