# =======================================
# Основные настройки
# =======================================
spring.application.name=book-store

# =======================================
# Подключение к БД
# Укажите актуальные данные вашего окружения
# =======================================
# allowPublicKeyRetrieval=true нужен для подключения к MySQL 8+ без SSL (локальная разработка)
spring.datasource.url=jdbc:mysql://localhost:3306/book_store?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=your_database_username
spring.datasource.password=your_database_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================================
# Настройки JPA / Hibernate
# =======================================
# false, чтобы избежать скрытых N+1 запросов и не держать коннект к БД на слое контроллеров
spring.jpa.open-in-view=false

# update генерирует схему под классы Entity (удобно локально)
# ВНИМАНИЕ: в проде использовать только validate или none во избежание потери данных
spring.jpa.hibernate.ddl-auto=update

# true для отладки генерируемых Hibernate запросов в консоли
spring.jpa.show-sql=true

# =======================================
# Настройки безопасности (JWT)
# =======================================
# Строго 256-битный ключ (или больше), иначе парсер JWT выбросит исключение
application.security.jwt.secret-key=your_secret_jwt_key
# Время жизни токена в миллисекундах (86400000 = 24 часа)
application.security.jwt.expiration=86400000

# =======================================
# Настройки бизнес-логики
# =======================================
# Дефолтный пароль для первичной инициализации аккаунта менеджера при старте
manager.password=your_secure_manager_password

# =======================================
# MINIO S3 STORAGE
# =======================================
minio.url=http://localhost:9000
minio.access.key=minioadmin
minio.secret.key=minioadmin
minio.bucket.name=book-covers